### ISSUE TITLE
button.loading should be deprecated

### ISSUE THREAD

**Issue by mattgallagher92** [Dzoukr/Feliz.DaisyUI#14]
It looks like the way daisyUI now represents [buttons with loading spinners](https://daisyui.com/components/button/#button-with-loading-spinner) is by having a span with the loading class as a child of the button. The Feliz.DaisyUI equivalent is

```fsharp
Daisy.button.button [
    button.primary
    prop.children [
        Daisy.loading
    ]
]
```

which renders nicely:

![image](https://github.com/Dzoukr/Feliz.DaisyUI/assets/46973220/620e8504-acde-41e8-ba49-cd2ef496a23b)

However, the Feliz.DaisyUI API implies that something like this is sensible

```fsharp
Daisy.button.button [
    button.primary
    button.loading
]
```

which doesn't render well:

![image](https://github.com/Dzoukr/Feliz.DaisyUI/assets/46973220/ce87f6a8-42e1-4417-9c4d-38a78a3b749f)

I recommend marking `button.loading` as deprecated, with a message advising use of Daisy.loading as a child instead.

**Comment by Dzoukr** [comment]
Good point, fixed now!
