### ISSUE TITLE
Collapsing menus and submenus does not work

### ISSUE THREAD

**Issue by des1sgm** [Dzoukr/Feliz.DaisyUI#17]
Hello, I am using the Safe Stack template and would like to use the DaisyUI menu with submenu. Unfortunately, collapsing the submenus does not seem to work.

**Comment by Dzoukr** [comment]
Hi @jdcheesy, look at the last example here: https://dzoukr.github.io/Feliz.DaisyUI/#/menu

Also, "collapsing submenus does not seem to work" is not very descriptive. 🤷

**Comment by des1sgm** [comment]
Hello @Dzoukr, thank you very much for the quick reply. I have found the problem. The menu works, but in the documentation the detail element (Html.details) is missing. 
Kind regards
Juergen
